import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

class AppTheme {
  static final lightMode = FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xff5959c1),
      primaryContainer: Color(0xffd6d6f5),
      secondary: Color(0xff3d3a69),
      secondaryContainer: Color(0xffcfcbe1),
      tertiary: Color(0xfff09d45),
      tertiaryContainer: Color(0xffffddb1),
      appBarColor: Color(0xffcfcbe1),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 10,
    appBarStyle: FlexAppBarStyle.background,
    transparentStatusBar: false,
    bottomAppBarElevation: 1,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 20,
      blendTextTheme: true,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      thickBorderWidth: 2,
      defaultRadius: 16,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.primary,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.primary,
      switchSchemeColor: SchemeColor.primaryContainer,
      switchThumbSchemeColor: SchemeColor.primary,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorBackgroundAlpha: 15,
      inputDecoratorRadius: 10,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
      fabSchemeColor: SchemeColor.primary,
      chipRadius: 10,
      popupMenuRadius: 6,
      popupMenuElevation: 6,
      alignedDropdown: true,
      useInputDecoratorThemeInDialogs: true,
      appBarScrolledUnderElevation: 8,
      drawerWidth: 280,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarMutedUnselectedIcon: false,
      menuRadius: 6,
      menuElevation: 6,
      menuBarRadius: 0,
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedLabel: false,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarMutedUnselectedIcon: false,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorOpacity: 1,
      navigationBarElevation: 2,
      navigationBarHeight: 70,
      navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
      navigationRailMutedUnselectedLabel: false,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationRailMutedUnselectedIcon: false,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 1,
    ),
    keyColors: const FlexKeyColors(
      useTertiary: true,
      keepPrimary: true,
      keepTertiary: true,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
  );
}
